#!/usr/bin/env python3
"""Read `.ai/solution-patterns.csv` and emit a deviation report.

Part of the solution-patterns skill. Zero required arguments — reads the CSV
generated by `pattern_map.py`, groups rows by deviation code, and prints a
human-readable summary (or JSON via --json).

The deviation codes (see skill §5):
  none              Nothing to report.
  ui-mismatch       ExpectedUiPath != ActualUiPath.
  ui-missing        Code file looks UI-facing but no route/menu reference found.
  test-missing      ExpectedTestPath does not exist.
  test-relocated    A test covers this file but from a non-canonical path.
  off-convention    Code path doesn't match any recognised pattern for its stack.

Examples:
  python validate_patterns.py                   # human-readable summary
  python validate_patterns.py --json            # JSON report
  python validate_patterns.py --fail-on test-missing  # exit 1 on matching deviation
"""
import argparse, csv, json, sys
from pathlib import Path

import detect_stack
from pattern_map import COLUMNS

SEVERITY = {
    "none": 0,
    "test-relocated": 1,
    "ui-mismatch": 2,
    "ui-missing": 2,
    "test-missing": 3,
    "off-convention": 3,
}

COLORS = {
    "none": "\033[32m",
    "test-relocated": "\033[33m",
    "ui-mismatch": "\033[33m",
    "ui-missing": "\033[33m",
    "test-missing": "\033[31m",
    "off-convention": "\033[31m",
}
RESET = "\033[0m"

def load_rows(csv_path: Path) -> list[dict]:
    with open(csv_path, encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        missing = [c for c in COLUMNS if c not in (reader.fieldnames or [])]
        if missing:
            print(f"Error: CSV missing required columns: {missing}", file=sys.stderr)
            sys.exit(2)
        return list(reader)

def group_by_deviation(rows: list[dict]) -> dict[str, list[dict]]:
    groups: dict[str, list[dict]] = {}
    for r in rows:
        groups.setdefault(r["Deviation"] or "none", []).append(r)
    return groups

def main():
    parser = argparse.ArgumentParser(
        description="Deviation report for solution-patterns (reads .ai/solution-patterns.csv).")
    parser.add_argument("--root", help="Repo root (auto-discovered if omitted)")
    parser.add_argument("--json", action="store_true", help="JSON output")
    parser.add_argument("--fail-on", action="append", default=[],
                        help="Exit 1 if any row has this deviation (may be repeated)")
    parser.add_argument("--show", default="all",
                        help="Which deviations to list in detail: 'all', 'non-none', or comma-list")
    args = parser.parse_args()

    root = Path(args.root).resolve() if args.root else detect_stack.find_repo_root(Path.cwd())
    csv_path = root / ".ai" / "solution-patterns.csv"
    if not csv_path.exists():
        print(f"Error: {csv_path} not found. Run pattern_map.py first.", file=sys.stderr)
        sys.exit(2)

    rows = load_rows(csv_path)
    groups = group_by_deviation(rows)

    if args.show == "all":
        show_set = set(groups.keys())
    elif args.show == "non-none":
        show_set = {k for k in groups if k != "none"}
    else:
        show_set = {s.strip() for s in args.show.split(",") if s.strip()}

    summary = {k: len(v) for k, v in groups.items()}

    if args.json:
        detailed = {k: v for k, v in groups.items() if k in show_set}
        print(json.dumps({"root": str(root).replace("\\", "/"),
                          "csv": str(csv_path.relative_to(root)).replace("\\", "/"),
                          "total": len(rows),
                          "summary": summary,
                          "rows": detailed}, indent=2))
    else:
        print(f"\nDeviation report: {csv_path.relative_to(root)}")
        print("-" * 60)
        for code in sorted(summary, key=lambda c: (-SEVERITY.get(c, 0), c)):
            colour = COLORS.get(code, "")
            print(f"  {colour}{code:18s}{RESET} {summary[code]:4d}")
        print(f"  {'total':18s} {len(rows):4d}\n")

        for code in sorted(show_set, key=lambda c: (-SEVERITY.get(c, 0), c)):
            if code == "none":
                continue
            rows_for = groups.get(code, [])
            if not rows_for:
                continue
            colour = COLORS.get(code, "")
            print(f"{colour}{code}{RESET} ({len(rows_for)}):")
            for r in rows_for[:25]:
                extra = ""
                if code == "test-missing":
                    extra = f"  expected: {r['ExpectedTestPath']}"
                elif code == "ui-mismatch":
                    extra = f"  expected: {r['ExpectedUiPath']}  actual: {r['ActualUiPath']}"
                elif code == "test-relocated":
                    extra = f"  actual: {r['ActualTestPath']}  expected: {r['ExpectedTestPath']}"
                print(f"  - {r['CodePath']} ({r['Role']}){extra}")
            if len(rows_for) > 25:
                print(f"    ... and {len(rows_for) - 25} more")
            print()

    if args.fail_on:
        for code in args.fail_on:
            if summary.get(code, 0) > 0:
                sys.exit(1)

if __name__ == "__main__":
    main()
